name: smawa
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  aws_rekognition_api: ^2.0.0
  path_provider: ^2.1.2
  go_router: ^13.1.0
  super_circle: ^1.0.0
  flutter_dotenv: ^5.1.0
  camera_windows: ^0.2.1+9
  camera: ^0.10.5+9
  progress_indicators: ^1.0.0
  animated_text_kit: ^4.2.2
  sizer: ^2.0.15
  sqflite: ^2.3.2
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.0+4
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/presentation.png
    - assets/home.png
    - assets/sphere.gif
    - assets/image1.jpg
    - assets/shoe1.png
    - assets/logo.png
    - assets/qrcode.png
    - secrets.env
